from contextlib import asynccontextmanager
from datetime import datetime
from fastapi import FastAPI
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from pathlib import Path

from src.config import HF_REPO_ID, INTERVAL_MINUTES
from src.hf_api import get_unannotated_datasets, create_pr
from src.annotate import annotate_dataset

scheduler = AsyncIOScheduler()


@asynccontextmanager
async def lifespan(app: FastAPI):
    scheduler.add_job(
        update,
        trigger="interval",
        minutes=INTERVAL_MINUTES,
        id="nth_minute_job",
        replace_existing=True
    )
    scheduler.start()
    print(f"APScheduler started. Watching '{HF_REPO_ID}' every {INTERVAL_MINUTES} minute(s).")

    yield

    print("Shutting down APScheduler...")
    scheduler.shutdown()


app = FastAPI(
    title="FastAPI Hugging Face Watcher",
    lifespan=lifespan
)

@app.get("/")
async def root():
    return {
        "status": "online",
        "watching_repo": HF_REPO_ID,
        "interval_minutes": INTERVAL_MINUTES
    }

@app.get("/update")
async def update():
    """Check for unannotated datasets and create pull requests for them."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        missing = get_unannotated_datasets()

        if missing:
            print(f"[{now}] {len(missing)} dataset(s) missing metadata.parquet ({HF_REPO_ID})")
            for folder_path in missing:
                print(f"[{now}] Annotating {folder_path}...")
                try:
                    ds_name = Path(folder_path).name
                    annotation = annotate_dataset(folder_path, ds_name)
                    pr_desc = (
                        f"This PR adds annotations for the `{ds_name}` dataset.\n\n"
                        "Generated by the Annotation Bot."
                    )
                    create_pr(str(annotation), f"{folder_path}/metadata.parquet", f"[bot] {ds_name} annotations", pr_desc)
                    print(f"Annotated {folder_path} successfully")
                except Exception as err:
                    print(f"Failed to annotate {folder_path}: {err}")
        else:
            print(f"[{now}] All datasets on '{HF_REPO_ID}' have metadata.parquet.")
    except Exception as e:
        print(f"[{now}] Error checking repository: {e}")
        
    return {"status": "Update complete."}


