name = "dynaword-annotation-server"
main = "src/index.js"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "dynaword_webhooks"
database_name = "dynaword-webhooks"
database_id = "4d5d93ed-41cc-4cb9-85dc-99be0da5d270"

[triggers]
crons = ["0 0 * * *"] # Run every day at midnight UTC

[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1